version: "3"
services:
  master:
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
    command:
      - /usr/local/spark/sbin/docker-master.sh
  slave:
    build: .
    links:
      - "master:master"
    command:
      - /usr/local/spark/sbin/docker-slave.sh
      - spark://master:7077
